defaults:
  - optimizer: adam_w

# compile model for faster training with pytorch 2.0
compile: false

output_dir: ${paths.output_dir}

sampler: null
source_energy_config: null
train_from_buffer: false
