defaults:
  - net: egnn_dynamics_ad2_cat
_target_: transferable_samplers.models.flow_matching_module.FlowMatchingModule
compile_net: false
train_from_buffer: false
mean_free_prior: true
atol: 1e-4
rtol: 1e-4
dlogp_tol_scale: 1.0
prior:
  _target_: transferable_samplers.models.priors.normal_distribution.NormalDistribution
  num_dimensions: ${data.num_dimensions}
  mean_free: true
sigma: 0.0
source_energy_config:
  _target_: transferable_samplers.utils.dataclasses.SourceEnergyConfig
  sample_batch_size: 8
  energy_batch_size: 8
  grad_batch_size: 8
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 5e-4
  betas: [0.9, 0.999]
  weight_decay: 0.0
