populate_buffer:
  _target_: transferable_samplers.callbacks.populate_buffer_callback.PopulateBufferCallback
  sampler: null
  evaluator:
    _target_: transferable_samplers.evaluation.evaluator.PeptideEnsembleEvaluator
