sampling_evaluation:
  _target_: transferable_samplers.callbacks.sampling_evaluation_callback.SamplingEvaluationCallback
  sampler: null
  evaluator:
    _target_: transferable_samplers.evaluation.evaluator.PeptideEnsembleEvaluator
  output_dir: ${paths.output_dir}
