name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*"]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Run pre-commits
        uses: pre-commit/action@v3.0.1
